# Generated by Django 5.1.4 on 2024-12-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favicon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
